type SearchResult {
    poster_path:       String
    popularity:        Float
    id:                Int
    overview:          String
    backdrop_path:     String
    vote_average:      Float
    media_type:        String
    first_air_date:    String
    origin_country:    [String]
    genre_ids:         [Int]
    original_language: String
    vote_count:        Int
    name:              String
    original_name:     String
    adult:             Boolean
    release_date:      String
    original_title:    String
    title:             String
    video:             Boolean
    profile_path:      String
}

type Genre {
    id:   Int
    name: String
}

type ProductionCompany {
    id:             Int
    logo_path:      String
    name:           String
    origin_country: String
}

type ProductionCountry {
    iso_3166_1: String
    name:       String
}

type SpokenLanguage {
    iso_639_1: String
    name:      String
}

type CreatedBy {
    id:           Int
    credit_id:    String
    name:         String
    gender:       Int
    profile_path: String
}

type LastEpisodeToAir {
    air_date:        String
    episode_number:  Int
    id:              Int
    name:            String
    overview:        String
    production_code: String
    season_number:   Int
    still_path:      String
    vote_average:    Float
    vote_count:      Int
}

type Network {
    name:           String
    id:             Int
    logo_path:      String
    origin_country: String
}

type Season {
    air_date:      String
    episode_count: Int
    id:            Int
    name:          String
    overview:      String
    poster_path:   String
    season_number: Int
}

type Movie {
    adult:                 Boolean
    backdrop_path:         String
    budget:                Int
    genres:                [Genre]
    homepage:              String
    id:                    Int
    imdb_id:               String
    original_language:     String
    original_title:        String
    overview:              String
    popularity:            Float
    poster_path:           String
    production_companies:  [ProductionCompany]
    production_countries:  [ProductionCountry]
    release_date:          String
    revenue:               Int
    runtime:               Int
    spoken_languages:      [SpokenLanguage]
    status:                String
    tagline:               String
    title:                 String
    video:                 Boolean
    vote_average:          Float
    vote_count:            Int
}

type TV {
    backdrop_path:        String
    created_by:           [CreatedBy]
    episode_run_time:     [Int]
    first_air_date:       String
    genres:               [Genre]
    homepage:             String
    id:                   Int
    in_production:        Boolean
    languages:            [String]
    last_air_date:        String
    last_episode_to_air:  LastEpisodeToAir
    name:                 String
    networks:             [Network]
    number_of_episodes:   Int
    number_of_seasons:    Int
    origin_country:       [String]
    original_language:    String
    original_name:        String
    overview:             String
    popularity:           Float
    poster_path:          String
    production_companies: [ProductionCompany]
    production_countries: [ProductionCountry]
    seasons:              [Season]
    spoken_languages:     [SpokenLanguage]
    status:               String
    tagline:              String
    type:                 String
    vote_average:         Float
    vote_count:           Int
}

type Query {
    search(query: String): [SearchResult]
    movie(id: ID): Movie
    tv(id: ID): TV
}
